### ISSUE TITLE
F24 Blue-Submarine - Firefox 47 description popups illegible, libreoffice toolbars

### ISSUE THREAD

**Issue by arehtykitna** [mate-desktop/mate-themes#126]
Hi, I'm currently using the GTK+2 build after a clean install. while for the most part it works very nicely, there are a couple of minor theme niggles to look at please guys. If it's something I need to change on my notebook please let me know. Thanks for your time and efforts as always

Firefox - white text on light blue description popups
![screenshot at 2016-06-22 15-10-10](https://cloud.githubusercontent.com/assets/7422283/16269974/750cb062-388c-11e6-9fa1-0b54324d3e83.png)

f24 mate-compiz x86_64 (1.14.0-1)
mate-themes 3.20.8-3
firefox 47.0-4

LibreOffice 5.1.4.2-1 - the toolbars at the top don't look right at all. there seems to be the charcoal colour overlaid on light blue (close button). It would be better to have all of it one or other if possible, preferably light blue? Has Fedora LO been switched from GTK+2 to GTK+3 recently?
![screenshot at 2016-06-22 15-20-04](https://cloud.githubusercontent.com/assets/7422283/16270064/d29cb6e6-388c-11e6-9ca0-acaa9b13a047.png)

**Comment by raveit65** [comment]
@arehtykitna 
Hi Mike,
i know, firefox-47 stiil ignore any fg color settings for tooltips.
This was all working well with firefox-46, try downgrade ff and you will see that tooltips fg colors are working.
I guess there is someting broken with firefox or they hardcode the fg color to white.
FF did hardcode a lot of stuff.
You will see that the fg color is fine if you use a theme with dark bg for tooltips, ie BlackMate or Adwaita ;)
Can you please file out a rhbz report about?
I'm waiting since 2 weeks for a report, i'd like to forward them to firefox.
Only those guys can say more about this annoying issue, or which selector in themes should used.

**Comment by arehtykitna** [comment]
On Wed, 22 Jun 2016 07:44:38 -0700
raveit65 <notifications@github.com> wrote:

> @arehtykitna 
> Hi Mike,
> i know, firefox-47 stiil ignore any fg color settings for tooltips.
> This was all working well with firefox-46, try downgrade ff and you
> will see that tooltips fg colors are working. I guess there is
> someting broken with firefox or they hardcode the fg color to white.
> FF did hardcode a lot of stuff. You will see that the fg color is
> fine if you use a theme with dark bg for tooltips, ie BlackMate or
> Adwaita ;) Can you please file out a rhbz report about? I'm waiting
> since 2 weeks for a report, i'd like to forward them to firefox. Only
> those guys can say more about this annoying issue, or which selector
> in themes should used.
> 
> ---
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub:
> https://github.com/mate-desktop/mate-themes/issues/126#issuecomment-227766784

Hi, no problem I'll open a ticket.

**Comment by raveit65** [comment]
Btw. LO have the same problems than firefox and they use gtk3.
1. you can't use gtk3-inspector to find the right selector for an element.
So, theming is ugly try&error and waste a lot of time.
2. they do not use GtkWidgets in favor of using gtk
3. I thing they use a mix of gtk2 and gtk3 elements, because come buttons acting more like gtk2 theming

To summary, theming ff an lo is a mess :)

**Comment by arehtykitna** [comment]
On Wed, 22 Jun 2016 08:10:35 -0700
raveit65 <notifications@github.com> wrote:

> Btw. LO have the same problems than firefox and they use gtk3.
> 1. you can't use gtk3-inspector to find the right selector for an
> element. So, theming is ugly try&error and waste a lot of time.
> 2. they do not use GtkWidgets in favor of using gtk
> 3. I thing they use a mix of gtk2 and gtk3 elements, because come
> buttons acting more like gtk2 theming
> 
> To summary, theming ff an lo is a mess :)
> 
> ---
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub:
> https://github.com/mate-desktop/mate-themes/issues/126#issuecomment-227775225

That's what I thought you'd say. I'm going to see if the upstream TDF
version is any better ;)

**Comment by arehtykitna** [comment]
This is the upstream version of LO 5.1.4.2 I just replaced it with and looks as it should do. Fedora packagers have created a GTK+2/GTK+3 package with an identity crisis by the looks of it :)

![screenshot at 2016-06-22 17-10-10](https://cloud.githubusercontent.com/assets/7422283/16274154/47bff410-389c-11e6-9107-9414b57a752d.png)

Worth another rhbz report? I don't really want to stick with Fedora's 5.1.X builds though as I'll be moving to 5.2 as soon as that is released.

**Comment by raveit65** [comment]
Hurray,
no report is needed for Lo, i can point everyone who blame me to this report here :smile:
Only for firefox, and please add the link here.

**Comment by arehtykitna** [comment]
I did, but here it is again ;) https://bugzilla.redhat.com/show_bug.cgi?id=1349041

**Comment by raveit65** [comment]
ff is fixed in fedora 24, so i'm closing this.
http://koji.fedoraproject.org/koji/buildinfo?buildID=774924

**Comment by arehtykitna** [comment]
yes, thanks for your guidance.
