### ISSUE TITLE
Tabs in GTk3 application under bluementa lacks spacing

### ISSUE THREAD

**Issue by smikkelsendk** [mate-desktop/mate-themes#130]
Mate 1.14.1 - Fedora 24
The first screenshot shows how pavucontrol is rendered with bluementa theme, and the second shows how it is rendered with blackmate theme. 

![bluementa](https://cloud.githubusercontent.com/assets/3275361/16765034/feb56d18-4831-11e6-9340-b71ba2f235f0.png)

![blackmate](https://cloud.githubusercontent.com/assets/3275361/16765037/00c3193e-4832-11e6-9bd3-75d15d76a7a0.png)

**Comment by raveit65** [comment]
Note, i need to test this a bit more, because pavu-control does not use a own style class and it is possible that i match other applications with that general styling for GtkNotebook.
GtkNotebook is used mostly everywhere in code of applications.
You can simply copy the changes in /usr/share/themes/BlueMenta/gtk-3.0/
or the the whole files from Gtk-3.20 branch.
I think you won't like it :)

**Comment by raveit65** [comment]
I have released new versions and build them for fedora.
But i had to removed the border color for the notebook in pavu-control because GtkNotebook is everywhere in applications code and i saw this border in virt-manager window.
Pavu-control needs to use a style class .frame for GtkNotebook like other preferences windows do.
Than it is possible to use
notebook.frame {
.........
}
in themes, which is used by other preferences windows.
Another prob is that a lot of gtk3 apps didn't add a specific style class on top for gtk+-3.20, to make this application unique for themes. For example we did that for all our applications.
Eg. for pluma we added the style class pluma-window at top level.
This makes it possible to style pluma independent from any other application.

I suggest to file out a RedHat bugzilla report against pavu-control for this.
I'm happy to discuss this there why this is needed for gtk+-3.20.

**Comment by smikkelsendk** [comment]
I don't know if this is related to the changes, but now if I have tabs in mate-terminal and hover it.. The tab graphics will do a odd kind of resize of the tab area.

![hover](https://cloud.githubusercontent.com/assets/3275361/17102836/b63120e2-527b-11e6-9375-3335f4df998c.png)

![nonhover](https://cloud.githubusercontent.com/assets/3275361/17102843/b80ea952-527b-11e6-959b-d843fd8d90d5.png)

**Comment by raveit65** [comment]
TraditionalOK theme?

**Comment by smikkelsendk** [comment]
TraditionalOK theme looks fine.. It happens for BlueMenta

**Comment by raveit65** [comment]
ok, thanks, i see it too
I will look into it.

**Comment by raveit65** [comment]
Yes it is related to changes for pavu-control.
But i can override this with
```
window.background.mate-terminal > box.vertical > notebook > header.top tab,
window.background.mate-terminal > box.vertical > notebook > header.top tab:checked,
window.background.mate-terminal > box.vertical > notebook > header.top tab:checked:hover {
    border-radius: 4px 4px 0px 0px;
    padding: 2px 2px 2px 6px;
    margin: 0px 0px 0px -1px;
    border-style: solid;
    border-color: @borders;
    border-width: 1px;
}
```
Good that we have add .mate-terminal as selector at top level.
This is very good example how important it is that application use specific selectors for gtk+-3.20.
Again, please file out a report against pavu-control.
If i found one app more which is broken because of settings for pavu-control i will revert this bullshit.

**Comment by smikkelsendk** [comment]
Do you want me to simply file a bug with Fedora team, or you want me to go directly to PulseAudio maintainers?

**Comment by raveit65** [comment]
Well, at least this is upstream issue and needs to befixed first there.
Applying the fix in fedora is the second step.
Please link the report here and i will post all needed infos there.

**Comment by smikkelsendk** [comment]
https://bugs.freedesktop.org/show_bug.cgi?id=97087
