### ISSUE TITLE
BlackMATE-chat title and text entry are black on gradient black - in hexchat

### ISSUE THREAD

**Issue by Gnalldo** [mate-desktop/mate-themes#134]
Also you can see squared white corners showing on those boxes.
I'm running Mint 18, Blackmate version is 3.18.1
![screenshot from 2016-07-27 17-24-30](https://cloud.githubusercontent.com/assets/12790631/17197449/a9bfc05a-5421-11e6-8dff-e0345b04d823.png)

**Comment by lukefromdc** [comment]
Looks like rounded corners over a white background, but I run GTK 3.21 and don't have any chat applications installed so have never seen this. My work on BlackMATE has been limited to the port to GTK 3.20 and 3.21.

**Comment by Gnalldo** [comment]
I updated to GTK 3.20, the issue is still there.   By the way, Thanks for the most usable dark theme I've ever seen.

**Comment by raveit65** [comment]
I don't see that with xchat and both hex/xchat use gtk2.
But someone told me the same about hexchat some days ago, There is a setting in hexchat preferences which causes the issue.

**Comment by raveit65** [comment]
Btw. using a theme version for gtk+-3.20 on a distro release with other gtk+  version is a bad idea.

**Comment by Gnalldo** [comment]
I'm keeping 3.18.1 , I'd put 3.20 in my ~/.themes folder so no harm in looking.

**Comment by raveit65** [comment]
Maybe , you don't know it.
gtk+-3.20 themes had a syntax change, they don't work with 3.18
and 3.18 themes will never work with 3.20
Thanks gtk+ dev for a complete rewrite of a theme.

**Comment by lukefromdc** [comment]
Since this is a GTK2 app it works no matter what GTK3 version or GTK3 theme version you have. Fire up a GTK3 application with the wrong theme version and you will see quite a nasty surprise, especially if one is GTK3.20 and the other GTK3.18.

I don't know enough about the GTK 2 portion of BlackMATE or about Hexchat to work on this. I don't know if this is some custom widget or just an oddball packing that puts a widget that has rounded corners (looks like an entry) over another widget that got a white background. GTK2 does not have GTK Inspector, though there is the 3ed party "GtkParasite" package that does a similar job.

**Comment by raveit65** [comment]
@Gnalldo 
In preferences category inputbox please disable the checkbox 'Use the text box font and colors'.
This solves the issue here :wink: 
![bildschirmfoto zu 2016-09-25 08-06-46](https://cloud.githubusercontent.com/assets/961604/18813348/86790282-82f7-11e6-9541-7b60d4de8e3b.png)
Can you confirm please?

**Comment by Gnalldo** [comment]
@raveit65 
Confirmed, that worked like a charm. I should have known there would be a simple solution that I was to blind to see. Thanks for the help.
