### ISSUE TITLE
BlackMATE Characters not different than background in Opera Browser (and others)

### ISSUE THREAD

**Issue by luiandresgonzalez** [mate-desktop/mate-themes#138]
Hi, 

While using opera browser, the popups that confirm exit navigation or grant access to camera or audio are not showing. 

**[EDIT] Distro:** 
Release 16.04.1 LTS (Xenial Xerus) 64-bit
Kernel Linux 4.4.0-36-generic x86_64
MATE 1.12.1
Output of  `dpkg -l libgtk2.0-0 libgtk-3-0`

`ii  libgtk-3-0:amd 3.18.9-1ubun amd64        GTK+ graphical user interface lib`

`ii  libgtk2.0-0:am 2.24.30-1ubu amd64        GTK+ graphical user interface lib`

This is with AmbianceMate:

[![popup opera.png](https://s11.postimg.org/q1ijgmws3/popup_opera.png)](https://postimg.org/image/ecejso5tb/)

And this is with BlackMATE:

[![opera popup.png](https://s11.postimg.org/c8jd7rk77/opera_popup.png)](https://postimg.org/image/clardy2gv/)

Other applications such as Mendeley Desktop have similar issues:

[![1.png](https://s10.postimg.org/401hll0yh/image.png)](https://postimg.org/image/u8cmayl1x/)

When switching to BlackMATE:

[![2.png](https://s14.postimg.org/sd28im3ht/image.png)](https://postimg.org/image/flo2c3tpp/)

When highlighting:

[![3.png](https://s12.postimg.org/zcgbznr1p/image.png)](https://postimg.org/image/syr8wem5l/)
##

**Comment by raveit65** [comment]
useless without posting distro , mate version and gtk+3 version.

**Comment by luiandresgonzalez** [comment]
@raveit65 , sorry. Edited with the requested information.

**Comment by lukefromdc** [comment]
I don't have Opera installed and do not used closed source browsers so cannot
debug Opera. My machines handle sensitive encrypted files, so closed source
programs are not permitted on them. Sorry about that but I'd have to set up
a whole extra box just to work on Opera.

Two questions that might help others though: Does Opera use GTK to draw its 
widgets or just as a backend like Firefox does, and does it block GtkInspector
like Firefox does?

With ANY program make sure your version supports the GTK version you have,
a  lot of the Firefox issues came up because the Mozilla devs did all their work
against GTK 3.18 and then GNOME totally changed the theming system for
GTK 3.20. If this is a browser only supporting GTK 3.18 it will presumably
catch up in time.

**Comment by lukefromdc** [comment]
This REALLY looks like an unsupported GTK version on the part of the browser

**Comment by raveit65** [comment]
Well, same here in fedora. Opera isn't in official repos and i've no clue what Mendeley Desktop is.
Do you know if opera use gtk3 or gtk2?

**Comment by Mikaela** [comment]
I cannot see the original screenshots as Firefox keeps telling me "server not found", but is it this the same issue?

![HexChat input box](https://user-images.githubusercontent.com/831184/45255019-3290a880-b38a-11e8-923c-1cf42b0d34a4.png)

This is HexChat's (2.14.1) inputbox. I found https://github.com/hexchat/hexchat/issues/1832#issuecomment-252193829 which says it should be fixed and mentions setting fixing this.

> You can just disable prefs > input > use text box color until you get that though.

**Comment by raveit65** [comment]
Issue is too old.
File out a new one if you think the problem still exists.

**Comment by lukefromdc** [comment]
I for one cannot work on Opera or issues related to it due to high security machines from which I have to blacklist closed software. Any issue with BlackMATE and a closed program will have to be dealt with by someone else on the team for that reason unless an open source program shows the same issue.
