### ISSUE TITLE
Green-Submarine 3.20.11 MATE top panel some applets are always highlighted

### ISSUE THREAD

**Issue by geki-yaba** [mate-desktop/mate-themes#141]
Since mate-themes 3.20.11 some applets, like date/time applet, are always highlighted. Looks kinda strange.

**Comment by raveit65** [comment]
I guess you mean that the backgound color of some applets are different with gtk3 panel.
fixed with https://github.com/mate-desktop/mate-themes/commit/040e91581f13d90e5fe1ab5b1548a9ee8408c275
For the moment please replace /usr/share/themes/Green-Submarine/gtk-3.0/mate-application.css with the file from 3.20 branch.
I will do a new release as soon as possible.

**Comment by geki-yaba** [comment]
Yes, they are different, a quite light color. We will see.

**Comment by raveit65** [comment]
fixed
