### ISSUE TITLE
BlueMenta WM theme: Inconsistent maximized frame_geometry

### ISSUE THREAD

**Issue by genpfault** [mate-desktop/mate-themes#150]
The "max" frame_geometry in `metacity-theme-2.xml` should match the `1` (`geometry_maximized`) and `3` (`max`) versions.

`metacity-theme-1.xml`:

    <distance name="left_width" value="0"/>
    <distance name="right_width" value="0"/>
    <distance name="bottom_height" value="0"/>

`metacity-theme-3.xml`:

	<distance name="left_width" value="0" />
	<distance name="right_width" value="0" />
	<distance name="bottom_height" value="0" />

But `metacity-theme-2.xml`:

    <distance name="left_width" value="1" />
    <distance name="right_width" value="1" />
    <distance name="bottom_height" value="1" />

The 1px left border causes the WM to swallow wheel events (even if the window otherwise has input focus!) in Firefox or MATE Terminal if the cursor is on the far left.

Using `mate-themes` 3.22.3-1 on Debian `testing`.

**Comment by raveit65** [comment]
No, there is a reason for the border. Otherwise you won't see any different to the panel and some people use vertical panels.
https://github.com/mate-desktop/mate-themes/commit/35ec318af73682a5f0604832dd03f59f8cd1fa3a
People did blame me in the past about that the panel has no visual border.
You only need to put the cursor over the scrollbar and everything is fine.
From a logical view this is correct.
Why should i get scroll events if i'm not over the scrollbar?
