### ISSUE TITLE
Cinnamon themes broken by 3.2.0 changes

### ISSUE THREAD

**Issue by leigh123linux** [mate-desktop/mate-themes#151]
https://github.com/linuxmint/Cinnamon/commit/7158824c25a5ee6a586568ddeb8c4b93e8432239

**Comment by raveit65** [comment]
https://github.com/mate-desktop/mate-themes/commit/eabd3f875bbf4f3107dfa5d3b18e09c6332b3c4a
@leigh123linux 
I will prepare a new release the next days

**Comment by leigh123linux** [comment]
Thank you.

**Comment by lukefromdc** [comment]
I just tested the new Cinnamon 3.2 themes, they all seem to work. These were quick tests with cinnamon --replace over a running mate session and killing the mate-panel to see the Cinnamon panel themes before the mate panel restarted under them. That was necessary because these panel themes are transparent. The menus (biggest Cinnamon 3.2 issue) all seemed to work fine.

**Comment by raveit65** [comment]
Thanks for testing
@lukefromdc 
Do you have any local changes for new releases?
@leigh123linux 
Do you want to push cinnamon-3.2 to epel7 ?
Than i will prepare a new release for gtk+-3.14 too.

**Comment by leigh123linux** [comment]
@raveit65 

Yes please to epel7

**Comment by lukefromdc** [comment]
I don't have any local changes to this as of now, in fact I pushed out a Debian package with last night's changes to my archive.org repo.
