### ISSUE TITLE
Nice light and dark theme, ugly themes away

### ISSUE THREAD

**Issue by JoDo77** [mate-desktop/mate-themes#153]
Hi! I'm just a normal user. I originally planned to write this on the forum, but the forum is locked, it seems.

I add my opinion. I think that would be enough one nice light theme and one nice dark theme, plus contrasting theme and inverse contrasting theme. But all nice and good quality. Other "ugly" motives available in a separate / additional package.

The current themes are not exactly nice. Of all major desktop environments probably the worst.

Otherwise, I like MATE and am happy with it. Thanks.

Sorry about the quality of my English.

**Comment by raveit65** [comment]
We don't ship only lovely themes.
Don't use a theme if you don't like it.

**Comment by lukefromdc** [comment]
Themes are totally subjective in terms of who likes what. That's why we ship so many.

**Comment by JoDo77** [comment]
OK, it is also a solution. But it's so user friendly? ;-)

...MATE wants to be ugly? :-)

How about making user survey, user research?

**Comment by lukefromdc** [comment]
Both gnome-look.org and DeviantArt(ad-supported site) offer pages and pages of GTK themes, and the work we've done to ensure sane defaults in themes not explicitly supporting MATE means you should be able to find one to your liking. No DE and no distro is able to please everyone with their default themes, which is why the ability of others to both write and distribute other themes is so important. If you can't write themes you can still find something closer to your liking than the defaults, download and install it. Just be absolutely certain to use the theme version matching your GTK3 version or you will see just how ugly things can REALLY get.

If you can and do write your own theme you can offer it for others to use. Usual starting point for that is to modify an existing theme, just as Adwaita was the initial starting point for writing most other GTK3 themes and in fact Adwaita's code and comments can be found in many other GTK3 themes.

**Comment by JoDo77** [comment]
The problem is not the quantity. The problem is the quality.

The only satisfactory theme is Ambiant-MATE, with comments.

If you're working on so many themes wasting energy. I think. At the expense of quality?

Linux Mint that has cleverly solved - color variations good quality theme. Light and dark versions. I have a similar view, a few lines above.

I have no knowledge on writing themes. I can contribute to crowdfunding, if you will. Now I donate regularly to the MATE.

Instead of "ugly", I could write a "poorer quality". But ugly is not so far from the truth. :-)

Even so, thanks for your time and answers. Good luck.

**Comment by kn00tcn** [comment]
jodo, you're thinking of having something like mint's new mate default, right? https://www.linuxmint.com/rel_sarah_mate_whatsnew.php

i believe ambiant-mate is ubuntu 'exclusive'? i dont like how these distros keep fragmenting the users, they need to send the themes here if they're that good, or is that going to make a mess of gtk versions?

if you want to see ugly, xfce's window border themes are worse, as are some of the small obscure DEs

blue menta is quite the nice official theme btw, it just needs a few tweaks to modernize it (a lot of the gtk3 update is already helping with that)

i am all about sane defaults as well, good design is about legibility, click target sizing, clarity such as icons describing their action like _ [] X instead of 3 dots, etc

we can probably keep the official ones since there arent that many, i havent checked what extra ones distros put in, but i am certainly planning to make a new theme with classic (a little 3d) & modern (flat) variants worthy of being defaults, not based on personal colors

**Comment by JoDo77** [comment]
I'm not expert. Only the user. It is only idea, proposal... I'll let the more experienced to develop these ideas and evaluate them.

Thank you for your time, considerations and work (including previous).

Linux Mint was cited as an example. It may not be exactly like this. :-)

**Comment by kn00tcn** [comment]
yes not exactly, the example is that mint has one official theme with the goal of matching user expectations & design patterns (it's also branded with the official mint green color)

the challenge in design is to always be subconscious, to be an enhancement, to guide the user, to not get in the way

users or those not familiar with design principles & design psychology wont know how to describe or make something good, but most will quickly feel something is wrong when it breaks the patterns

anyway, in mate's case, the gtk themes are pretty solid (in fact i couldnt stop using bluementa when trying xfce), it's the window decorators are a problem so i'll probably make a new simple clean one eventually

**Comment by JoDo77** [comment]
I mostly agree. And I remind you that MATE want to be an "INTUITIVE and ATTRACTIVE desktop environment" as written in the introduction to the homepage.

People like things that look good and that work. MATE should target regular users, not just geeks and nerds. :-)
