### ISSUE TITLE
less_dark_color in BlackMATE appears to be white

### ISSUE THREAD

**Issue by ondrejch** [mate-desktop/mate-themes#177]
When BlackMATE theme is selected, caja-view window has white background which makes it unusable. It seems the less_dark_color is not initialized properly.

**Comment by ondrejch** [comment]
Oooops, solved by deleting ~/.config/caja/ directory.

**Comment by lukefromdc** [comment]
I cannot duplicate this and get a dark color on the caja-view windows with BlackMATE and always have. I will now test the latest version of mate-themes from GIT master to see if something just broke it.

Which mate-themes version, which GTK version, and which Caja version is this? If Caja 1.12 or earlier is built with GTK 3.20 or later the caja-view color will be wrong in most themes due to changes in GTK itself.
