### ISSUE TITLE
mate 1.18: look and feel of standard themes changed, no way to restore previous look and feel

### ISSUE THREAD

**Issue by giorgiob** [mate-desktop/mate-themes#178]
After I switched to mate 1.18 on Manjaro, I noticed that the look and feel of some themes (e.g. BlueMenta) has changed. E.g., the workspace switcher now uses a gradient instead of a solid colour for its background. Are the themes with the previous look and feel still available under another name? If not, I think this should be the case so that users can choose whether they want to switch to the new themes or stay with an existing one.

Summarizing:
(1) Existing themes should be kept when introducing new ones, possibly (1.a) using a new name for the new theme or (1.b) using the existing name for a new theme and renaming the existing theme.
(2) If (1) is already implemented, all the themes should be included in a standard mate distributions. E.g. in Mate 1.18/0 / Manjaro there is only a new version of the BlueMenta theme and as far as I know it is not possible to restore the previous one.

**Comment by raveit65** [comment]
I do not agree,  feel free to fork BlueMenta and do what ever you want with it.

**Comment by lukefromdc** [comment]
It's worth keeping in mind that 1.18 is the first version of MATE that can only be built with GTK3, and that GTK 3.20 and later radically changed the theming code, breaking all previous GTK3 themes. Massive amounts of work went into dealing with the GTK 3.20 issue. Making the GTK3 and GTK2 versions of a theme match exactly is also exceptionally difficult.  

I had to do all of this to keep a theme resembling the circa 2008 UbuntuStudio theme in my own systems when GTK 3 came along. The UbuntuStudio team went in a different direction, switching to XFCE to avoid GNOME 3, and did not port the old theme. Did that myself as a result, at first very crudely but in much greater detail as I learned how. Then along came GTK 3.20, trashing all my previous work and forcing a do-over.  Hardest part was getting a near-exact match between GTK2 and GTK3, which forced use of a lot more images that would otherwise have been necessary. Many GTK2 theme engines were never ported to GTK3, and ALL theme engines became deprecated in GTK3 as of GTK 3.14. No idea if they work now.

Since the GTK2 UbuntuStudio theme used the "murrine" engine (at that time did not exist in GTK3) to draw things like checkboxes, I iiterally had to screenshot them out of GIMP's gui and use images cut from them in GTK3! Conversely some GTK3 elements I liked had to be done this way to duplicate them in GTK2.

Anyway, if you want an exact theme that never changes as GTK changes underneath it, that's a lot more work than just keeping a theme looking approximately as it did before. Can be done if you want to take up the effort yourself: pick your favorite version of the theme in question, fork it, and port it to the exact GTK 3 version you need to use it with. You will probably then want to match the GTK2 version to it. The "pixmap" engine in GTK2 will let you use the screenshotted images of GTK3 theme elements not supported in GTK2. In GTK3, images are supported directly in the css coding, so that's a bit easier. 

Here's a debugging issue with GTK3 I learned the hard way:  Just one missing image causes GTK3 to go bonkers and some versions of GTK3 will get drawing failures, so when installing your custom theme make sure you can get to another theme (have a dconf-editor window open and don't stop your session) just in case you mess up the paths to your images or they don't end up where you expected them to when you install.

**Comment by giorgiob** [comment]
@raveit65: I did not know it was technically so difficult because of the dependencies on GTK, sorry if I posted a request in the wrong project. I have considered forking the theme myself, but it will be no use if the underlying engine keeps changing rapidly.

I admit I am a bit confused right now: I moved from gnome to mate because mate seemed more stable but if I understand correctly the recent development of GTK make it pretty hard to have a stable look and feel.

@lukefromdc 

> It's worth keeping in mind that 1.18 is the first version of MATE that can only be built with GTK3, and that GTK 3.20 and later radically changed the theming code, breaking all previous GTK3 themes. Massive amounts of work went into dealing with the GTK 3.20 issue. Making the GTK3 and GTK2 versions of a theme match exactly is also exceptionally difficult.

I honestly do not understand this policy. One of the advantages of OSS should be that it gives the user the choice to switch to a new technology without being forced to. So I would understand if they had improved the implementation and added new features in GTK 3.20, but I do not understand why they broke backward compatibility.

So, if it is more a GTK issue, I will consider starting a discussion there.

Thanks a lot for the feedback.

**Comment by raveit65** [comment]
gtk2 and gtk3 is complete different and gtk3 offers us much more possibilities in theme styling.
In other words " Why should a ferrari looks like a fiat ?"
So i do not agree that a theme under gtk3 should look same as with gtk2.
If you like that a theme  looks like gtk2 the next 1000 years use Traditional themes.
They are made for looking like gtk2.
And  honestly , i like the gradient for workspace switcher.
Why should i don't do what i like as theme artist?
I mean i am spending my time that BlueMenta is working under gtk3 , not you.
Don't worry, you can override everything as user with creating such a file.
~.config/gtk-3.0/gtk.css

**Comment by mrnhmath** [comment]
> So I will probably have to tweak the themes myself.
I'd like to see them :)

**Comment by lukefromdc** [comment]
One point about GTK3: The GTK devs stabilized GTK3 at GTK 3.22 because a change they wanted for the next version would have forced Firefox and Libreoffice to start over on their ports to GTK3. The theming for GTK3 should never change again once you have updated to the GTK 3.22 final version. I don't see MATE porting to GTK4 for quite a while (if ever), and GTK4 is not itself out yet except as 3.90. GNOME said they did this so other projects would have a stable modern version of GTK.
