### ISSUE TITLE
scroll buttons lost in mozilla applications after upgrading to mate-themes 3.22.14

### ISSUE THREAD

**Issue by pionnunnio** [mate-desktop/mate-themes#197]
#### MATE general version
1.18

#### Package version
3.22.14-1

#### Linux Distribution
Fedora 26

**before:**
![before](https://user-images.githubusercontent.com/32462931/31089635-de24d1e6-a772-11e7-8ae7-a362283f68b1.png)

**after:**
![after](https://user-images.githubusercontent.com/32462931/31089642-e40b626e-a772-11e7-882c-371e7c01d47c.png)

this affects firefox and thunderbird in at least the following themes:
menta
traditionalok

**Comment by raveit65** [comment]
Confirmed, this is a collateral damage by a fix for yelp/evolution/webkitgtk4.
https://github.com/mate-desktop/mate-themes/commit/5923eed2cfce3d15529f43b3cee47787bf4b6ee7
But as you can see we use *scrollbar.horizontal {}* in this commit.
Firefox or other mozilla apps should respect *horizontal* and  don't use this setting for vertical scrollbars.
This is seriously a mozilla bug and they should simply use GtkWidgets from Gtk+ and not their half backed own gtk stuff.
I am so tired about theming mozilla and gtk3.
Should i prefer  mozilla or yelp/evolution, or should i hang myself?
I seriously suggest to file out a report against firefox at rhbz. I happy to show their devs whats going  wrong with their code.

**Comment by lukefromdc** [comment]
Trouble is, Firefox is a "must-have, must-work" app for a lot of people, especially those who do not trust Google Chrome. Thus, it is probably necessary to favor Firefox.  My own theme requires a userChrome.css file to work with Firefox, but I don't know if distros have any way to install that systemwide so any Firefox install can use it.

There are LOTS of complaints by a LOT of people about what Mozilla devs are doing, but simply no real competitor where privacy is needed and full extension support is needed. Firefox 57 is said to work much better with dark GTK themes-but a lot of people are not going to install it because it no longer supports legacy extensions!  Unless all the extensions I use catch up, I can't use FF 57 for instance.

**Comment by pionnunnio** [comment]
this affects the horizontal scrollbar in libreoffice writer as well (e.g., in print preview, if i zoom to 100%, on my computer a horizontal scrollbar appears, and is missing the buttons).

**Comment by pionnunnio** [comment]
@raveit65 -- i hope you don't really feel that way, and i hope you know your work is appreciated!

I have posted an issue at rhbz, per your request: https://bugzilla.redhat.com/show_bug.cgi?id=1498681

**Comment by xhorak** [comment]
@raveit65 Hi, what's wrong in Firefox? That stepper buttons can be shown for horizontal and hidden for vertical scrollbars and vice versa and Firefox does not respect that?

**Comment by sc0w** [comment]
I suggest revert https://github.com/mate-desktop/mate-themes/commit/c6524047d2313ca39316616c2f4a8115f8cb75c9

I prefer the issue in yelp instead the problems with firefox / libreoffice

btw, how to reproduce the issue in yelp? I can't find horizontal scrollbars, where is it?

**Comment by lukefromdc** [comment]
There is a possible way to apply this to Yelp and ensure it stays off of Firefox. Haven't tested it but it is simple. Pulled the "widget chain" from a GtkInspector view of Yelp, though GtkInspector does not show the scrollbar because it does not go below the widget, which is "YelpView" but that is not a valid selector in GTK 3.20+.

```
window box box overlay widget scrollbar.horizontal {
	-GtkScrollbar-has-backward-stepper: false;
	-GtkScrollbar-has-forward-stepper: false;
}
```
and if this does not work in Yelp play with the selectors until you find one that works. Given that FF does not use normal GTK widgets, this should be almost sure not to match anything in FF. As a more general rule this should work almost anytime it is necessary to exclude Firefox from something

**Comment by raveit65** [comment]
@xhorak 
> Hi, what's wrong in Firefox? That stepper buttons can be shown for horizontal and hidden for vertical scrollbars and vice versa and Firefox does not respect that?

Yes, in that commit i disabled the scrollbar.horizontal stepper for yelp/webkitgtk4
https://github.com/mate-desktop/mate-themes/commit/5923eed2cfce3d15529f43b3cee47787bf4b6ee7
```
scrollbar.horizontal {
	-GtkScrollbar-has-backward-stepper: false;
	-GtkScrollbar-has-forward-stepper: false;
}
/* override for normal applications */
scrolledwindow > scrollbar.horizontal {
	-GtkScrollbar-has-backward-stepper: true;
	-GtkScrollbar-has-forward-stepper: true;
}
```
But firefox use this setting for vertical.scrollbars too.

**Comment by raveit65** [comment]
btw, how to reproduce the issue in yelp?

@sc0w 
Ie. first page of atril (with the info button)
You will see the horz scrollbar if you resize the yelp window.
Without the commit you see redraws at the place of the horz scrollbar.

But i noticed a abrt alarm of webkitgtk4 with the setting now.
I think i will revert this commit.
Also the hint from @lukefromdc doesn't work.

**Comment by lukefromdc** [comment]
I could not reproduce the Yelp issue either, though steppers were incorrectly rendered. My own theme does not contain anything like https://github.com/mate-desktop/mate-themes/commit/c6524047d2313ca39316616c2f4a8115f8cb75c9 and I have never had redraw problems in Yelp. Best bet may be revert the whole mess

**Comment by raveit65** [comment]
reverted from all branches a4807e437e6f2f98bec44b547288c2dfef73b699
@pionnunnio 
Simply remove the code by hand in your theme files for the moment.

**Comment by sc0w** [comment]
@raveit65 thanks

@lukefromdc I can confirm the yelp issue here in traditional ok

and, I am wondering, why atril shows that horizontal scrollbar? it is useless

**Comment by lukefromdc** [comment]
@sc0w Which version of Yelp are you running, and which version of GTK 3.22? I've got Yelp 3.22.0 and GTK 3.22.21. Wonder why Yelp 3.24 has not appeared, much less 3.26 either at all or in Debian Unstable?

**Comment by lukefromdc** [comment]
Also I've got libglib2.0-0 2.54 compiled locally

**Comment by sc0w** [comment]
@lukefromdc
yelp 3.22.0
gtk 3.22.21
debian testing

**Comment by sc0w** [comment]
evince (3.25.92) doesn't have yelp issue, it doesn't show the horizontal scrollbar

**Comment by lukefromdc** [comment]
I just got Yelp 3.26-and have been able to confirm a redraw issue affecting
only the bottom scrollbar, in any tyheme giving a a stepper except my own.

I think some kind of difference in using image files suppresses this on 
UbuntuStudio_Legacy, I will try to find the diference today or tomorrow.

Also-my first attempt to test this in BlueMenta with Firefox also running led 
to a total GUI lockup, though the VT consoles stll worked.

**Comment by lukefromdc** [comment]
I am on the road now, can't log into Github w/o my passphrase 
text files but I found this piece of code works. 

scrollbar.horizontal {
	-GtkScrollbar-has-backward-stepper: false;
	-GtkScrollbar-has-forward-stepper: false;
}

/*override for everything else*/

* scrollbar.horizontal {
	-GtkScrollbar-has-backward-stepper: true;
	-GtkScrollbar-has-forward-stepper: true;
}

Turns out the Yelp scrollbars don't respond to anything unless
they are the FIRST selector in a widget chain, and this is not 
true of Firefox so the code above strips the offending steppers
from Yelp but not from Firefox. 

The down side is that Libreoffice works this way too on many
widgets, so steppers disappear from LIbreoffice horizontal
scrollbars but at least Libreoffice vertical scrollbars still get
steppers. Our own apps are not affected, getting all their
steppers

I have seen people reject a theme entirely over absence of steppers,
you'd think GTK devs would be more careful about this. GTK 3.22
included one commit that was supposed to greatly speed up rendering
certain widgets with a lot of smaller widgets inside (lists I think) but created
redraw problems all over the place.

**Comment by raveit65** [comment]
> and, I am wondering, why atril shows that horizontal scrollbar? it is useless

Yes, it is useless, but i see the problem yelp from caja, eom, pluma  too.
Only  with yelp started from mate-terminal the horz scrollbar/redraw issues  isn't there :-)
First i thought it is a problem with webkitgtk because of the abrt (fedora bugreporting tool) with webkitgtk, and we have a report about same problem with evolution.
https://github.com/mate-desktop/mate-themes/issues/195
But maybe it is a problem with the yelp pages itself as mate-terminal isn't affected.

I will reopen the report.......

**Comment by raveit65** [comment]
All this brainfuck with theme workarrounds could be easily fixed if developers from gtk+-3 applications like firefox, thunderbird or OpenOffice or any others add a specific style class at the top of the widget chain, ie. 
.firefox or .libreoffice.
Then theme artist can easily fix issues with an application without hitting any other.
But why making an application easy if we can make (easy) more trouble ;-)

@lukefromdc 
i will test you ideas

**Comment by lukefromdc** [comment]
I have another test coming too: In my theme Yelp is OK, and all the scrollbar elements are images. I am going to test an explicitly specified image for the -gtk-icon-source in the button and see if it works in Menta

**Comment by lukefromdc** [comment]
I think I just found the exact cause of this in  the them: Yelp (and presumably any other affected applications) do not like the minimum height being set on the buttons. Setting a small minimum height (like the 10px in my theme) causes the scrollbar to be partially rendered, some of it visible but the bottom of it pushed out of the window and not shown, as here:
![yelp_w_10px_min-height-scrollbar_button](https://user-images.githubusercontent.com/14036792/31311255-5a5d2e50-ab76-11e7-850e-648511c3febe.png)

Setting a  larger minimum height like the 13px in Menta (or not setting it at all in some cases) causes the redraw bug. My guess is this rendering error pushes the scrollbar all the way off-window and creates the redraw.

The fix that makes the scrollbars look alike with steppers in Yelp is this, as odd as it seems:

```
scrollbar.horizontal button,
scrollbar.horizontal .button {
    min-width:10px;
    min-height: 0px;
    padding: 0px 1px;
}

```
The min-height gets changed to 0px (height still expands to fit scrollbar), but note the the min-width is still REQUIRED or the buttons won't be rendered at all. In my theme I will do this as
```

/*Workaround for Yelp scrollbar redraw bug caused my minumum height */
scrollbar.horizontal button{
	min-height: 0px;
}

```
And use it for a while to see if this creates other issues

**Comment by sc0w** [comment]
@lukefromdc 

yes, **`min-height: 0px;`** in **`scrollbar.horizontal button`** fixes the redraw issue

but, the stepper buttons in the horizontal scrollbar (yelp) doesn't work, and, in libreoffice the steppers are gone

**Comment by lukefromdc** [comment]
I don't see any chance of fixing all the problems in Firefox, Yelp, and Libreoffice at the same time due to the combination of bugs in GTK3 and non-standard use of GTK in Firefox and Libreoffice. This is bad enough that in some cases even Adwaita does not work right.

I have been trying to get scrollbars absolutely consistant between Pluma and Caja in my theme, and it seems to be impossible

**Comment by raveit65** [comment]
Ok, using *min-height: 0px;* brings back the horz scrollbar, but they are not full displayed.
Same as in screenshot from ubuntu-theme-legacy.
With Blue-Submarine:
![yelp-blue-submarine](https://user-images.githubusercontent.com/961604/31315460-68fb4476-ac19-11e7-921a-7999495cfe52.png)
And i see a little *redraw-issue area* on top of the scrollbar after resizing the window, which is exactly the size of the missing part at bottom of the scrollbar.

> but, the stepper buttons in the horizontal scrollbar (yelp) doesn't work, and, in libreoffice the steppers are gone

Confirmed.

I am not sure to replace a hack with another hack only for yelp and damage OpenOffice.
For me this looks more and more like an issue with yelp, and it works only with adwaita because they dropped the scrollbar buttons.
Personal yelp isn't important enough for me to file out a report at gnome bugzilla ;-)

I think we should find out why yelp displays a useless horz. scrollbar in some of our applications.
For me mate-terminal yelp page does the right thing.

**Comment by lukefromdc** [comment]
Check out https://github.com/lukefromdc/gtk-theme-ubuntustudio-legacy/commit/556ef747ebdb344848a0ef0684409b6e0e8c2b57 on my theme, which gives perfectly rendered scrollbars with perfectly useless steppers on Yelp. The scrollbars are actually in the right place-but it looks like steppers simply don't work in Yelp at all. Probably some buggy code in the way

**Comment by raveit65** [comment]
Ok, i got it working with Blue-Submarine after a clean up of previous hint from https://github.com/mate-desktop/mate-themes/issues/197#issuecomment-334537919
Sadly, using *min-height = 0px* only for yelp doesn't work.
```
scrollbar.horizontal button,
scrollbar.horizontal .button {
    min-width:16px;
    min-height: 13px;
    padding: 0px;
}

/* yelp */
window box box overlay widget scrollbar.horizontal button {
    min-height: 0px;
}
```
So, using only
```
scrollbar.horizontal button,
scrollbar.horizontal .button {
    min-width:16px;
    min-height: 0px;
    padding: 0px;
}
```
breaks horz scrollbar buttons from libreoffice.
That using a widget chain from gtk-inspector doesn't work for scrollbar > buttons of yelp is another hint that something is really broken in that code.

**Comment by lukefromdc** [comment]
I just found there is NO way to distinguish Libreoffice from Yelp in the theme, both responding to exactly the same selectors. This compromise code gives undersize icons in usable horizontal scrollbar buttons in libreoffice, and renders the scrollbar a bit low in Yelp (with a corrupted area only a couple px wide). Vertical scrolbars are normal in libreoffice, and both vertical and horizontal buttons work. If you sacrifice the button icons with too small a min-height in Libreoffice, the buttons don't work right.

Libreoffice is probably a lot more important than Yelp in terms of minor rendering artifacts, and nothing can make the steppers actually work in Yelp. Similarly, nothing can remove them from Yelp and leave them in a horizontal scrollbar in Libreoffice. Until one or the other is fixed, this is the best we can do.

```
/*Workaround for Yelp scrollbar redraw bug caused my minumum height */
/*Compromise for working steppers in Libreoffice, partial horiz scrollbar display in Yelp*/
scrollbar.horizontal button{
	min-height: 8px;
	min-width: 14px;
}

/*Keep this off as many scrollbars as possible */
/*Also ensure arrow icons same size vertical and horizontal */
scrollbar.horizontal button{
	min-height: 8px;
	min-width: 14px;
}

scrollbar.vertical button{
	min-height: 14px;
	min-width: 14px;
}

```

**Comment by raveit65** [comment]
I think i will leave it like it is for Menta/Submarine/GreenLaguna theme.
@lukefromdc @sc0w 
Feel free to add the workaround for Traditional/BlackMate themes if you think this is good enough.

**Comment by lukefromdc** [comment]
Added the workaround to BlackMATE:
https://github.com/mate-desktop/mate-themes/commit/6cebca6eddd174561a586e0cd00587dffd4e4bec
for master and
https://github.com/mate-desktop/mate-themes/commit/3531b374675f2f33579cf242529c36e8409bcd7a
for 3.22

**Comment by joakim-tjernlund** [comment]
Just tested the new BlackMATE scrollbar code for evolution and it seems to work.
In other themes it doesn't redraw the horizontal scrollbar (or crashes webkit-gtk)

Could we have the BlackMATE fixes in the other themes too?

**Comment by joakim-tjernlund** [comment]
Ping? The current release has been broken for a long time now

**Comment by joakim-tjernlund** [comment]
ping?

**Comment by joakim-tjernlund** [comment]
I just tested to use adwaita-icon-theme as Custom Controls in TOK and now evolution has
a nice/working horizontal scrollbar. Maybe there is some magic in there MATE can use?

**Comment by joakim-tjernlund** [comment]
Some what off question, I got Adwaita theme installed too but MATE does not show
Adwaita as a full them I can choose. Where/what does MATE look for in order to
list a Theme?
The odd thing is that I can see ContrastHighInverse and HighContrast which are part of GNOME themes just like Adwaita

**Comment by raveit65** [comment]
> Some what off question, I got Adwaita theme installed too but MATE does not show
Adwaita as a full them I can choose. 

You need to edit their index.theme file. `MetacityTheme=....` is missing.
Eg.
```
[root@mother rave]# cat /usr/share/themes/Adwaita-dark/index.theme | grep MetacityTheme
MetacityTheme=DustBlue
```

**Comment by joakim-tjernlund** [comment]
> > Some what off question, I got Adwaita theme installed too but MATE does not show
> > Adwaita as a full them I can choose.
> 
> You need to edit their index.theme file. `MetacityTheme=....` is missing.
> Eg.
> 
> ```
> [root@mother rave]# cat /usr/share/themes/Adwaita-dark/index.theme | grep MetacityTheme
> MetacityTheme=DustBlue
> ```

Yes, now I can see Adwaita themes, thanks.
There does not seem to be any option in gnome themes to include Metacity, it would be nice if MATE could somehow
not require this setting.

**Comment by raveit65** [comment]
Well, gnome drop the metacity theme entry some years ago without no reason.
Some people ask for adding it again , but sadly gnome disagreed.
They do not really care about users of their software if not using gnome-hell.
So, why we should fix their problems and ignorance?
Try to file out an issue at gnome, it would be the easiest if they add a metacity theme again.

**Comment by raveit65** [comment]
And for better understanding why we can't fix it.
What you see in m-a-p is a mixed thumbnail generated from 3 components (gtk-theme, icon-theme and metacity-theme)
It is impossible to generate a thumbnail if one component is missing.
