### ISSUE TITLE
Feature request - GTK3 Fedora Blue-Submarine Theme

### ISSUE THREAD

**Issue by arehtykitna** [mate-desktop/mate-themes#86]
Hello, would it be possible to have the more minimal panel handle style from the GTK2 version of Blue-Submarine in GTK3? I'm not a huge fan of the chunkier full height dimpled handles and they don't work with a transparent panel background very nicely.

**Comment by NiceandGently** [comment]
Hi Mike,
you mean the big buttons to to hide a panel?
This is GTK3.......
I didn't style them in the theme, and i'm not shure if it's possible.
But i will look into it.

**Comment by arehtykitna** [comment]
Hi, no I mean the drag handles. Would it be better if I add a couple of screenshots to illustrate?

**Comment by NiceandGently** [comment]
Yes, please

**Comment by arehtykitna** [comment]
Fedora MATE GTK+3 Panel showing grab handles highlighted with badly drawn red circles ;)
![fedora mate-compiz gtk_3](https://cloud.githubusercontent.com/assets/7422283/7898876/0f8e7350-0706-11e5-96fa-2e03a319c6c5.png)

Fedora MATE GTK+2 Panel showing preferred style of grab handles
![mategtk2](https://cloud.githubusercontent.com/assets/7422283/7898877/0f95df64-0706-11e5-99e6-aacb65081591.png)

**Comment by NiceandGently** [comment]
Ahh, ok
i've fix that for bluementa theme already.
The panel is now complete transparent and i've add an image instead of the ugly build in grip.
It is neccessary to style the grip because it is the only way to move those applets and to have a right-click area.
Can you please test https://admin.fedoraproject.org/updates/mate-themes-1.10.1-0.2.git20150530.a0a9b98.fc22?_csrf_token=6fbb27c4526031b28a1cc81f594c346e897e4728
to see if you like the image for the grip.
I don't find anyother image to use, but if you are good in creating one or have another, i'm happy to use it for submarine themes.

**Comment by arehtykitna** [comment]
those BlueMenta grip images work okay for my purposes as they are at least to my eyes completely invisible. I'm not sure if that was your intention though.the transparency for menu and clock is indeed working fine though. Below are the GTK2 grip I am referring to I think. I managed to extract from the themes folder. I tried creating a custom theme with them. I can't however get them to load by converting to SVG via GIMP and renaming as appropriate for each Blue-Submarine theme subdirectory.

![handle-h](https://cloud.githubusercontent.com/assets/7422283/7899436/cc44f94c-071a-11e5-84bf-b67bb301864d.png)
![handle-v](https://cloud.githubusercontent.com/assets/7422283/7899437/cc4d2004-071a-11e5-8bc7-eae42b186f91.png)

**Comment by NiceandGently** [comment]
Hi Mike, submarine themes are from mate-themes-extras :)
Let us talk there.
https://github.com/NiceandGently/mate-themes-extras/issues/5

**Comment by NiceandGently** [comment]
i start moving submarine themes to mate-themes

**Comment by NiceandGently** [comment]
done!
3e3584a9cbfad011dbbbc6ddb707c9743d587db4
