### ISSUE TITLE
HIDPI support

### ISSUE THREAD

**Issue by wyatt8740** [mate-desktop/mate-themes#99]
Not sure if this goes here, but I'm seeing that MATE lacks special support for displays with very high DPI's. I guess this is not so much a bug as a feature request, but as older displays like mine age and people upgrade, it might be important in the future.

**Comment by raveit65** [comment]
Well, for HIDPI support Mate needs complete ported to  gtk3. We are on the way and for some few apps the transition is done. But most apps can be compiled with gtk3 but they have issues.
There are unofficial repos for fedora or archlinux where Mate is compiled with gtk3.
Closing this because it is the wrong package for a reguest.

**Comment by wyatt8740** [comment]
alright, thabks for letting me know.
